### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by Marinovs** [1Oreo/FUT19-Auto-Sniper#1]
Can you explain how to use. i tried but i can't start it!

**Comment by 1Oreo** [comment]
I've added a prerequisite section, which lists the actions you need to take before making the script work. if you have any other problems we'll need to debug them.

**Comment by badboyromal** [comment]
You cannot call a method on a null-valued expression.
At C:\Users\Admin\Desktop\module\FutModule.psm1:108 char:5
+     $Token = $almostString.Substring($almostString.IndexOf("identity. ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull


I think theres a bug in line 107, 107, 108 and 195.

**Comment by 1Oreo** [comment]
In general, extracting the session tokens from google chrome wasn't an easy task (I've searched a lot on how to do it, both on GitHub and google, and I couldn't find a good solution). what I did was accessing temp files (which windows likes saving) that contain google chrome session tokens and extracting them. This wasn't the prettiest ways of doing so but it worked on my machine and my friends machine. there's another option, of course, and that is to alter the code a bit (it used to look that way when I started using it on my machine, before uploading it to GitHub) and that is to extract the tokens from chrome using developer tools and sending them as a parameter to the relevant ps function. If you know a better way of extracting those tokens I'm happy to hear and alter the code or if you want to submit a pull request ill look into it. 
btw, I haven't touched this project for a while so I don't remember everything as I did when I wrote it.

**Comment by badboyromal** [comment]
Ahh, okay!
Well im trying to learn coding, and i thought that this would be a fun
project to start with. (I love Fifa)
If it isn't to much trouble, would you be able to make a short guide on how
to get access to the token, and where to put it in the file?

I appreciate the response!

Den tir. 26. feb. 2019 kl. 12.37 skrev Or Asaf (Oreo) <
notifications@github.com>:

**Comment by 1Oreo** [comment]
if you want to start coding I don't think this is the best project for a couple of reasons. mainly, the process of identifying how the entire fut web app works, takes a bit of time and understanding of more than just simple coding, you need to understand http requests, javascript etc. so Im not sure this is the best project for someone starting to code and I think you should look at the code when you're a bit more experienced with these topics. ps. PowerShell is an awesome language (I love it) but im not sure its the best language for beginners.
if you need anything els id be happy to help.

**Comment by badboyromal** [comment]
Thank you very much for the response!
I'm taking courses in NodeJs and Javascript currently, and i know a little
about HTTP request, but not that much tho.

But to make the auto sniper code work, i'd have to find the sessionID (
Token) and say $Token = '(SessionID)'?
Or should i find the directory on PC, where the chrome token is, and then
write in the path?



Den tir. 26. feb. 2019 kl. 20.44 skrev Or Asaf (Oreo) <
notifications@github.com>:
